services:

  garage:
    image: dxflrs/garage:${GARAGE_VERSION:-latest}
    # network_mode: "host"
    restart: unless-stopped
    environment:
      - GARAGE_ADMIN_TOKEN=${GARAGE_ADMIN_TOKEN}
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./${GARAGE_CONFIG_FILE:-garage.toml}:/etc/garage.toml
      - ./meta:/var/lib/garage/meta
      - ./data:/var/lib/garage/data
